# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:
   - jekyll-coffeescript
# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            IVY
tagline:          'Interactive Verification of Paramterized Systems'
description:      'Artifact Evaluation'
url:              https://apanda.github.com/ivy
baseurl:          /

author:
  name:           'Oded Padon'
  url:             ''

# Custom vars
version:          2.1.0
